name: Document
on:
  schedule:
    # * is a special character in YML so you have to quote this string
    - cron: '5 3 1,15 * *'
#  push:
#    branches:
#      - master
jobs:
  document:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Package
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt
          
      - name: Document
        run: |
          sphinx-apidoc ./ -o ./docs/source/modules/
          sphinx-build ./docs/source/ ./docs/html/

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Documentation "
          body: "Created documentation using sphinx"
          lables: Documentation
          branch: documentation
          assignees: gmarupilla
          reviewers: gmarupilla
